name : build and test the back end of the project

on :
  push :
    branches : ["master"]

jobs :
  build_test :
    name : build and test the back of our app
    runs-on : self-hosted

    steps :
      - name : checkout code
        uses : actions/checkout@v3
      - name : SetUp JDK 17
        uses : actions/setup-java@v3
        with :
          java-version : '17'
          distribution : 'temurin'
          cache : maven
      - name : Run unit tests
        run : mvn -B test --file pom.xml
      - name: Build the back side app
        run : mvn -B package --file pom.xml

  publish-job:
    runs-on: self-hosted
    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging_back && cp target/*.war staging_back
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging_back