name : build and test the front end of the project

on :
  push :
    branches : ["master"]

jobs :
  build_test :
    name : build and test the front of our app
    runs-on : ubuntu-latest

    steps :
      - name : checkout code
        uses : actions/checkout@v3
      - name : Set up JDK 17
        uses : actions/setup-java@v3
        with :
          java-version : '17'
          distribution : 'temurin'
          cache : maven
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npm run cypress:run
      - name : Build the front side app
        run : mvn -B package --file esieaFront/pom.xml

  publish-job :
    runs-on : ubuntu-latest
    needs : build_test
    steps :
      - uses : actions/checkout@v3
      - uses : actions/setup-java@v3
        with :
          java-version : '17'
          distribution : 'temurin'
      - run : mvn --batch-mode --update-snapshots -f esieaFront/pom.xml verify
      - run : mkdir staging_front && cp esieaFront/target/*.war staging_front
      - uses : actions/upload-artifact@v3
        with :
          name : Package
          path : staging_front